name: Run Puppeteer Script

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node automation.js
